# Netlify build and deploy settings

[build]
  # Command to build your React/Vite frontend
  command = "npm run build"
  
  # Directory where your serverless functions live
  functions = "netlify/functions"
  
  # Directory where the built frontend is located
  publish = "dist"

# Local dev settings for `netlify dev`
[dev]
  command = "npm run dev" # Command to start your Vite dev server
  port = 5173             # Port your Vite server runs on
  publish = "dist"        # Folder with your static assets
